### ISSUE TITLE
Legend doesn't show up the first time.

### ISSUE THREAD

**Issue by arnajdas1992** [carbon-design-system/carbon-charts#190] opened 2019-02-12 02:08 UTC
#### I am submitting a...

- [ ] Design defect

#### charts version:
0.8.6

### Issue description
The legend doesn't render the 1st time the charts load. When it re renders or when page is reloaded, the legend shows up.

#### Steps to produce the issue
In our scenario, we have 3 tabs in our code. The 1st tab has the charts. When the page loads, the legends don't show up. But when we switch tabs and come back to the 1st tab, the legends show up.

### Screenshot or recording
<img width="388" alt="screenshot 2019-02-12 at 7 34 05 am" src="https://user-images.githubusercontent.com/46365045/52606576-1c3acb80-2e99-11e9-9661-e384253f8c9f.png">

<img width="379" alt="screenshot 2019-02-12 at 7 34 14 am" src="https://user-images.githubusercontent.com/46365045/52606577-1cd36200-2e99-11e9-9edf-12a94b5382f2.png">

**Comment by theiliad** [comment] 2019-02-12 02:10
So this seems to be a rare case of this issue, I haven't seen it in other places where donut chart is used.

Could you make a codesandbox or describe a way to reproduce the issue please?

**Comment by arnajdas1992** [comment] 2019-02-12 03:47
I think this happens when you wrap the chart in a div with a fixed height and width. I tried having the chart separately and didn't face this issue. Whenever the chart is confined in a div, this issue occurs.

**Comment by theiliad** [comment] 2020-01-08 15:26
Fixed by #275.

Feel free to re-open if issue still persists. I tested in Chrome, Safari & Firefox.

**Closed by theiliad** 2020-01-08 15:26 UTC
Labels: bug 🐛, core
