### ISSUE TITLE
[fix]: ERROR TypeError: Cannot use 'in' operator to search for 'focus' in null

### ISSUE THREAD

**Issue by liliangbo** [carbon-design-system/carbon-charts#1229] opened 2021-11-29 03:13 UTC
### Question

![image](https://user-images.githubusercontent.com/36925115/143802869-38fd3c11-c87c-4ea3-b426-6366285a18ae.png)

When I click on the toolbar, the following error occurs！
![image](https://user-images.githubusercontent.com/36925115/143802822-dfdd0d15-7670-4e7b-b36d-0370dd6d84ba.png)

**Comment by Akshat55** [comment] 2021-11-29 03:58
Hi @liliangbo!
Could you please share the chart data & options? This can better help us debug this issue.

**Comment by haozhelee** [comment] 2021-11-30 09:22
I found the reason.
The effect I want is to set the loading in the options to true before the data is passed in, and then change the loading to false after the data is obtained.
The problem now is that the chart can be rendered normally, but this error occurs when you click the more button in the toolbar.
It may be that my usage is wrong, what should I do if I want to achieve my needs? Thank you

![image](https://user-images.githubusercontent.com/26142398/144019204-ff0c44ed-ca7e-4aba-8535-0f284ca585e5.png)
![image](https://user-images.githubusercontent.com/26142398/144019280-aacf6b41-da89-437b-8ac5-00257486b873.png)
![image](https://user-images.githubusercontent.com/26142398/144019323-fe3a3af9-2dcc-4e2c-99a5-d83119ad3191.png)

**Comment by Akshat55** [comment] 2021-12-02 04:26
@liliangbo, That is great that you found the reason. 

Take a look index.js file in the code sandbox link below for a loading example. The chart data & options are updated after 5 seconds to replicate a async behavior.

https://codesandbox.io/s/winter-snow-w1lh4?file=/src/index.js

If the above has answered your question, please close the issue.

**Comment by haozhelee** [comment] 2021-12-02 09:44
谢谢你的回复，
我按照链接里的例子，它可以奏效。但是我想实现的是可以多次切换，我每次查询数据之前都需要设置loading为true，异步响应以后，把loading设置为false。
当我这样做的时候，这个问题又出现了。请问这个loading状态是只能改变一次吗？还是我的做法不正确呢？

![image](https://user-images.githubusercontent.com/26142398/144396852-7f433776-e3de-446b-81a0-3189e40a1372.png)
![image](https://user-images.githubusercontent.com/26142398/144397235-a67e0081-34e1-491f-a24c-e8762051259e.png)

**Comment by Akshat55** [comment] 2021-12-03 02:52
Hi, @haozhelee, what exactly is the issue? Could you perhaps create a code sandbox with the error? 

I'm assuming you're using `setTimeout` to replicate an API call as an example here... other then that your approach seems fine.

What do you mean by: 

> Can this loading status only be changed once?

This all comes down to how you set up your requests. From what I understand, you need to call a function on the select option change, that function will set the chart loading to true. When you get your data, you need to update the data and then set loading to false.

I have updated the demo to give you an example of the data changing behaviour on a button click.
https://codesandbox.io/s/winter-snow-w1lh4?file=/src/index.js

**Comment by haozhelee** [comment] 2021-12-06 01:59
Sorry, maybe I didn't describe it clearly.
Your example is very good. You can also see here that when the first loading is over, click the show more button in the toolbar, and the drop-down box can be displayed normally. But after clicking get data, when the loading state ends, and then click the show more button in the toolbar, this error will occur.
This is the issue.
![image](https://user-images.githubusercontent.com/26142398/144775088-681e087f-54a8-4060-ad33-a42c2f171475.png)
![image](https://user-images.githubusercontent.com/26142398/144775114-4589a7cc-22ae-432e-8d59-f89ccb145a86.png)

**Comment by Akshat55** [comment] 2021-12-07 04:40
Thanks, I can reproduce the error.

**Closed** 2021-12-07 20:37 UTC
Labels: enhancement

**Comment by haozhelee** [comment] 2021-12-08 08:03
Thank you
