### ISSUE TITLE
[Regression] X-axis doesn't render long strings gracefully

### ISSUE THREAD

**Issue by kalai001** [carbon-design-system/carbon-charts#526] opened 2020-03-10 07:51 UTC
#### I am submitting a...

- [ ] Feature request
- [ ] Design defect
- [x] Source code defect
- [ ] Demo/documentation defect
- [ ] Other

#### charts version:
0.29.8

### Issue description
X-axis labels were handled gracefully in earlier versions of Carbon charts. Long string was getting wrapped. Now, the long strings aren't handled at all. It ends up compressing the graph area.

#### Steps to produce the issue
https://codesandbox.io/s/peaceful-hertz-wwoqn

#### Current behavior
X-axis label keeps expanding and compresses the graph area

#### Expected behavior
Label should wrap or truncate with ellipsis. The graph are should remain un-affected

### Screenshot or recording
![image](https://user-images.githubusercontent.com/46040341/76290692-a25e5700-62d1-11ea-9b2b-38a56640dadc.png)

**Comment by theiliad** [comment] 2020-03-11 04:16
Duplicate of #347

**Comment by theiliad** [comment] 2020-06-24 03:05
Closed by #646

**Closed by theiliad** 2020-06-24 03:05 UTC

**Comment by kalai001** [comment] 2020-06-24 09:08
@theiliad , What version of chart has this fix? I don't see it working with `v0.32.9`. Check this [sandbox](https://codesandbox.io/s/cranky-mcnulty-q2vu1?file=/src/index.js)

**Comment by theiliad** [comment] 2020-06-24 16:09
There's been an error with the release after merging that PR. This would be available in `0.32.10`. Let me check why it's errored out

**Comment by theiliad** [comment] 2020-06-24 23:19
Fixed, please try `0.32.11`

**Comment by kalai001** [comment] 2020-06-28 00:06
Works fine on `0.32.11`
