### ISSUE TITLE
Bar chart label overlap

### ISSUE THREAD

**Issue by kimbaz** [carbon-design-system/carbon-charts#812] opened 2020-09-21 12:08 UTC
#### I am submitting a...

- [ ] Feature request
- [X] Design defect
- [ ] Source code defect
- [ ] Demo/documentation defect
- [ ] Other

#### charts version:
```json
"@carbon/charts": "0.38.2",
"@carbon/charts-react": "0.38.2",
```

### Issue description
When the time scale dataset is reduced from multiple days to a single day (using custom ticks) the x-axis displays an overlapped text

#### Steps to produce the issue
1. Use custom ticks;
2. Set the dataset to at least 7 days (ticks);
3. Change the chart state using a dataset that contains a single day (tick);

#### Current behavior
The text (date and time) on the x-axis is overlapped;

#### Expected behavior
It should be displayed only the label for the current day;

### Screenshot or recording
7 Days:
<img width="931" alt="image" src="https://user-images.githubusercontent.com/20518828/93764520-2beccb00-fc0b-11ea-8b87-5da144a61979.png">

Single day:
<img width="940" alt="image" src="https://user-images.githubusercontent.com/20518828/93764557-3d35d780-fc0b-11ea-996b-b1507e3291a6.png">

**Comment by theiliad** [comment] 2020-09-21 16:26
Hi, just tested on `0.38.3`, I'm unable to reproduce this issue.

![bar-overlap (1)](https://user-images.githubusercontent.com/14989804/93794019-913dbd80-fc05-11ea-8ca2-110d0c83e201.gif)

I will close for now, but if this is still happening for you then feel free to re-open with a codesandbox example where the issue is reproduced. It is important that we can reproduce the issue in order to debug.

**Comment by kimbaz** [comment] 2020-09-22 11:45
@theiliad here is the code example. not sure why codesandbox is overlapping even with the first dataset though:
https://codesandbox.io/s/carbon-charts-react-forked-fbhg2?file=/src/index.js
https://fbhg2.csb.app/

**Comment by theiliad** [comment] 2020-09-22 15:34
Oh I see, this has to do with a bug that @natashadecoste is working on

**Comment by kimbaz** [comment] 2020-09-22 15:48
Thanks!

**Comment by kimbaz** [comment] 2020-09-23 10:05
@theiliad I can still reproduce it (0.38.5) on both sandbox and our app:
https://codesandbox.io/s/carbon-charts-react-forked-fbhg2?file=/src/index.js
<img width="979" alt="image" src="https://user-images.githubusercontent.com/20518828/93998289-3b475200-fd8c-11ea-957c-96b888416011.png">

I had a look at the html and it seems that when the ticks are scaled down some information are repeated:
<img width="903" alt="image" src="https://user-images.githubusercontent.com/20518828/93998588-a8f37e00-fd8c-11ea-9fa5-3406f69562e3.png">

**Comment by theiliad** [comment] 2020-09-23 14:19
Ok, I'll follow again with @natashadecoste

**Comment by kimbaz** [comment] 2020-09-23 14:24
Thanks if you need more information or code from my side please let me know.

**Comment by kimbaz** [comment] 2020-09-23 16:06
not sure this might help but I temporarily fixed the issue using this custom formatter:
```js
ticks: {
  formatter: (e) => {
    if (indexOf(ticksList, e) !== -1) {
      return moment(e).format('D');
    }
    return null;
  },
  values: ticksList
}
```

**Comment by natashadecoste** [comment] 2021-03-03 16:32
It seems that updating axis tick values _is working in the latest carbon-charts codebase_
Modified the codesandbox slightly: https://codesandbox.io/s/carbon-charts-react-forked-0qr3i


https://user-images.githubusercontent.com/14351335/109838409-21038100-7c14-11eb-91f4-bf0d632f8115.mov

**Comment by ninja511** [comment] 2021-03-08 15:40
closing, working as designed.

**Closed by ninja511** 2021-03-08 15:40 UTC
Labels: bug 🐛
