### ISSUE TITLE
[React] Wrong version in package.json

### ISSUE THREAD

**Issue by marcinmot** [carbon-design-system/carbon-charts#268] opened 2019-05-07 15:00 UTC
After installing charts-react version 0.11.11 package.json constains wrong version 0.11.10.
Content of package.json file:

```json
{
  "_from": "@carbon/charts-react@0.11.11",
  "_id": "@carbon/charts-react@0.11.11",
  "_inBundle": false,
  "_integrity": "sha1-HpIU8FEN9iVLVJynsIh3GiI4AxE=",
  "_location": "/@carbon/charts-react",
  "_phantomChildren": {},
  "_requested": {
    "type": "version",
    "registry": true,
    "raw": "@carbon/charts-react@0.11.11",
    "name": "@carbon/charts-react",
    "escapedName": "@carbon%2fcharts-react",
    "scope": "@carbon",
    "rawSpec": "0.11.11",
    "saveSpec": null,
    "fetchSpec": "0.11.11"
  },
  "_requiredBy": [
    "/"
  ],
  "_resolved": "https://na.artifactory.swg-devops.com:443/artifactory/api/npm/igc-npm-virtual/@carbon/charts-react/-/charts-react-0.11.11.tgz",
  "_shasum": "1e9214f0510df6254b549ca7b088771a22380311",
  "_spec": "@carbon/charts-react@0.11.11",
  "_where": "C:\\Users\\MarcinMotyka\\workspace\\gov-quality-ui",
  "author": {
    "name": "IBM"
  },
  "bugs": {
    "url": "https://github.com/IBM/carbon-charts/issues"
  },
  "bundleDependencies": false,
  "contributors": [
    {
      "name": "Eliad Moosavi",
      "email": "iliadm@ca.ibm.com",
      "url": "https://github.com/theiliad"
    }
  ],
  "dependencies": {
    "@carbon/charts": "^0.11.10"
  },
  "deprecated": false,
  "description": "Carbon charting components for React",
  "devDependencies": {
    "@storybook/addon-options": "5.0.5",
    "@storybook/react": "5.0.5",
    "@storybook/storybook-deployer": "2.8.1",
    "babel-cli": "6.26.0",
    "babel-core": "6.26.0",
    "babel-loader": "7.1.2",
    "babel-plugin-external-helpers": "6.22.0",
    "babel-plugin-transform-object-rest-spread": "6.26.0",
    "babel-plugin-transform-react-jsx": "6.24.1",
    "babel-preset-env": "1.6.1",
    "babel-preset-react": "6.24.1",
    "base64-inline-loader": "1.1.0",
    "css-loader": "0.28.7",
    "img-loader": "2.0.0",
    "node-sass": "4.10.0",
    "react": "16.6.3",
    "react-dom": "16.6.3",
    "rollup": "0.67.3",
    "rollup-plugin-babel": "3.0.4",
    "rollup-plugin-commonjs": "9.2.0",
    "sass-loader": "7.1.0",
    "style-loader": "0.19.0",
    "url-loader": "0.6.2"
  },
  "homepage": "https://github.com/IBM/carbon-charts#readme",
  "license": "Apache-2.0",
  "main": "index.js",
  "maintainers": [
    {
      "name": "Eliad Moosavi",
      "email": "iliadm@ca.ibm.com",
      "url": "https://github.com/theiliad"
    }
  ],
  "name": "@carbon/charts-react",
  "peerDependencies": {
    "react": "^16.6.3",
    "react-dom": "^16.6.3"
  },
  "publishConfig": {
    "access": "public"
  },
  "repository": {
    "type": "git",
    "url": "git+ssh://git@github.com/IBM/carbon-charts.git"
  },
  "scripts": {
    "build": "bash build.sh",
    "clean": "rm -rf dist demo/bundle",
    "demo:build": "build-storybook -o demo/bundle/react",
    "start": "npm run storybook",
    "storybook": "start-storybook -p 9006 -c .storybook -s ./assets",
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "version": "0.11.10"
}

```

**Comment by cal-smith** [comment] 2019-05-07 18:34
Yep, we're working through some issues with our build system and npm deploys right now ... we'll update once it's resolved :+1:

**Comment by cal-smith** [comment] 2019-05-07 18:59
try `0.11.15` it should be resolved now :+1:

**Comment by marcinmot** [comment] 2019-05-08 08:57
Unfortunately it still is not working as desired. When installing `0.11.15` module gets installed with version `0.11.14`.
It was working fine till version `0.11.5`, from `0.11.6` charts-react module gets installed always with earlier version.

**Comment by cal-smith** [comment] 2019-05-08 15:15
I'll reopen this one and poke the packages some more ... If you have a minimal repro environment I'd like to take a look at that too

**Comment by theiliad** [comment] 2019-05-08 15:32
Thanks for bringing this up to our attention.

We’ll take a look soon and fix the issue, however the wrappers merely
mirror the core functionality, so as long as you’re on the latest version
of the core package, you will have access to everything that’s new.

**Comment by theiliad** [comment] 2019-06-03 18:38
Closing this as I just confirmed my installed version matches the latest on NPM (0.12.0).

If this happens again, feel free to reopen

**Comment by kalbert312** [comment] 2019-08-19 15:24
I'm running into this issue. IDE is spamming me with notifications to update because of the version mismatch.

<img width="1354" alt="carbon-problem" src="https://user-images.githubusercontent.com/5498623/63277735-dad60f00-c273-11e9-876d-28dde793dcd5.png">

**Comment by theiliad** [comment] 2019-08-19 15:26
@kalbert312 I see the issue. Will push a fix soon, thanks.

**Comment by kalbert312** [comment] 2019-08-19 17:46
Thanks. I'll also add that when I install another package with npm (e.g `npm i d3-scale`), it automatically uninstalls `@carbon/charts` and `@carbon/charts-react` for some reason (even though it's still in the `package.json`). I have to run `npm i` to reinstall those packages.

**Comment by theiliad** [comment] 2019-08-19 18:02
hmm... have you tried yarn @kalbert312. Yarn does a much better job of checking dependency conflicts and ranges

**Comment by kalbert312** [comment] 2019-08-19 18:31
I have, but I kept running into issues with it related to dependencies and switched back to `npm`. That was a while ago though.

**Comment by theiliad** [comment] 2019-08-19 18:46
@kalbert312 I mainly use yarn, there might have been issues in the past, specially in the beginning, but now I would say yarn gives you a smoother experience

**Comment by vpicone** [comment] 2019-10-08 22:38
We're using yarn and this is still an issue for us. The actual package version always lags behind the published version by 1 release. Fresh install:
<img width="374" alt="Screen Shot 2019-10-08 at 5 10 20 PM" src="https://user-images.githubusercontent.com/4078018/66438195-a0762c00-e9f1-11e9-88b6-9f7263bf5143.png">

**Closed** 2019-10-09 18:40 UTC
