### ISSUE TITLE
Tooltip configuration option needed

### ISSUE THREAD

**Issue by asahlin** [carbon-design-system/carbon-charts#207] opened 2019-03-08 16:31 UTC
I am submitting a...

- [x ] Feature request
- [ ] Design defect
- [ ] Source code defect
- [ ] Demo/documentation defect
- [ ] Other

charts version:
0.10.2

Issue description
Tooltip is hard coded to **dataset label**: value, which doesn't make sense in some cases.

Steps to produce the issue
Any bar chart

Current behavior
Tooltip is hard coded to **dataset label**: value

Expected behavior
Tooltip should be configurable or provide custom render function.   This allows Tooltip to be **x-axis label**: value or provide units, etc..

Screenshot or recording
![image](https://user-images.githubusercontent.com/13006634/54041431-52642600-418d-11e9-8fe6-fb30a5f3d7ef.png)

Endgoal: 
![image](https://user-images.githubusercontent.com/13006634/54041526-8e978680-418d-11e9-8ede-a2babf29be12.png)

**Comment by cal-smith** [comment] 2019-03-27 17:56
looks like this is a duplicate of #174

**Closed by cal-smith** 2019-03-27 17:56 UTC
